name: Build Windows installer

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri Windows installer
        run: npm run tauri:build -- --target x86_64-pc-windows-msvc
      - name: Show generated files
        shell: pwsh
        run: |
              Write-Host "Generated files:"
              Get-ChildItem -Path "src-tauri/target/release" -Recurse | Select-Object FullName

      - name: Upload Windows bundle
        uses: actions/upload-artifact@v4
        with:
          name: Repetytorium-POS-Windows
          path: src-tauri/target/release/bundle/**
          if-no-files-found: error
